<template>
  <div class="container">
    <nav class="nav">
      <ul>
        <li>
          <!-- Page routing!-->
          <router-link to="/" class="nav-item">Home</router-link>
        </li>
        <li>
          <router-link to="/projects" class="nav-item">Projects</router-link>
        </li>
        <li>
          <router-link to="/blog" class="nav-item">Blog</router-link>
        </li>
        <li>
          <router-link to="/contact" class="nav-item">Contact</router-link>
        </li>
      </ul>
    </nav>

    <h3 style="color: #b9bbbe">🚧Currently being Developed🚧</h3>
    <h4 style="color: #b9bbbe">
      This is a showcase of the finished projects i have~! I am trying to do
      better about having documentation of my work.
    </h4>
    <button @click="pickRandomString">Pick Random Name Mc Server</button>
    <p style="color: white">{{ randomLine }}</p>
  </div>
</template>


<script>
export default {
  data() {
    return {
      randomLine: "null",
    };
  },
  methods: {
    async pickRandomString() {
      try {
        const response = await fetch("./serverList.txt");
        console.log("??");
        if (!response.ok) {
          throw new Error("Error fetching the file");
        }
        var fileContents = `purple.wtf
akumamc.net
play.vipermc.net
pvp.land
mc.hypixel.net
astralmc.cc
play.wildprison.net
oplegends.com
coldpvp.com
sagepvp.org
bridger.land
skyblock.net
dynamicpvp.net
archermc.net
enchantedmc.net
play.schoolrp.net
play.zedarmc.com
sololegends.net
og-network.net
stray.gg
minemen.club
ghostly.live
mcplayhd.net
play.rinaorc.com
lunar.gg
mineshards.com
bwhub.net
esta.land
play.pvplegacy.net
ilovecatgirls.xyz
bedwarspractice.club
cylonemc.net
play.airidale.net
play.stickymc.com
mc.universocraft.com
2b2t.org
mc.lotc.co
kokscraft.pl
play.molean.com
mc.gommehd.net
mc.hycraft.us
play.ecc.eco
play.topstrix.net
play.valenamc.net
holypvp.net
leonemc.net
mushmc.com
server.playmonumenta.com
play.cubecraft.net
play.labs-mc.com
coralmc.it
mcpvp.club
invadedlands.net
zonecraft.es
blotcraft.com
anarchy.tf
hypixel.pl
edaters.live
exodusmc.org
play.manacube.net
minehut.com
horny.ltd
mcstyles.pl
egirlsarehot.xyz
play.mc-drugs.com
play.jackpotmc.com
minemenclub.com
mc.hydracraft.es
sp.spworlds.ru
blockmania.com
munchymc.com
evilmc.us
hylex.net
vanic.gg
mc.dogecraft.net
play.originrealms.com
laby.wtf
play.spworlds.ru
technoblade.club
play.wynncraft.com
astrely.cc
mush.com.br
play.direskies.net
crystalpvp.cc
play.coldnetwork.net
play.oc.tc
mineheart.net
flamemc.com.br
roxbot.com
librecraft.juegos
syuu.net
play.oplegends.com
minecraftsexserver.club
play.roxbot.com
oldfag.org
craftplay.pl
tubnet.gg
skywars.com
centrumpvp.pl
0b0t.org
mush.gay
icantjoinlmfao.club
librecraft.com
5b5t.org
hylexmc.net
gladmc.com
funcraft.net
play.vallenmc.net
eupvp.net
mineplay.pl
earthmc.net
donutsmp.net
fucks.party
faderealms.net
herobrine.org
minemora.net
roleplayhub.com
play.survival-games.cz
glance.top
play.mcmanhunt.com
play.jartexnetwork.com
2b2t.xin
stevec.at
mccentral.org
tabmc.pl
dracolegend.net
imaginefun.net
rgmc.pl
blocksmc.com
play.craftrise.tc
8b8t.me
zedarmc.com
hylex.gg
6b6t.org
9b9t.org
play.coldpvp.fr
play.minelatino.com
minecraftonline.com
pvphub.me
cobra.gg
arefy.net
luckynetwork.id
9b9t.com
constantiam.net
purityvanilla.com
acentramc.com
eu.sonoyuncu.network
blotcraft.net
play.minecadia.com
play.vanillaplus.net
craftmc.pl
themcx.com
play.stoneworks.gg
nauticmc.net
sub.shield.land
mc.gamster.org
mc.zotticraft.net
mc.minebox.es
play.pika-network.net
play.z-mc.net
play.minemalia.com
kiwismp.fun
2b2t.com.au
mc.spreen.world
hypixel.gay
kotsu.live
pikanetwork.net
dreamsmp.mc-srv.com
play.teslacraft.org
mc.emeraldcraft.com.ar
play.mineville.org
volatik.net
play.zedar.xyz
acmc.pl
mc.universocraft.net
play.hielkemaps.com
catpvp.xyz
mc.spworlds.ru
zalupa.online
wdsj.net
mineverse.com
supercraft.es
play.oceprestige.net
3fmc.com
play.seichi.click
rapy.pl
luckynetwork.net
moxmc.net
play.hypers.fun
boat1337.com
play.loverfella.com
sa.beedom.net
buckytour.com
nobokik.likes-kitten.tk
mcmeu.com
omegacraft.cl
crafted.pl
fakepixel.fun
simpcraft.com
wreeper.top
namemc.cam
mc.mineblaze.ru
vipermc.vorexservices.net
cpvp.pl
hidemypa.in
play.trexmine.com
nssv.pl
play.creativefun.net
kiroscraft.net
bitch.games2day.tk
survival-games.cz
mc.ecuacraft.com
vimeworld.net
mcmanhunt.com
play.sonoyuncu.network
armamc.com
originrealms.com
play.lifesteal.rip
anarchia.gg
mc-prison.com
cubecraftgames.net
minestar.pl
virtualhit.es
roleplayhub.net
mcteams.com
main.mcparks.us
technoblade.dreamsmp.club
firevanilla.net
play.smpearth.com
rederevo.com
mc.comugamers.com
mc.zedarmc.com
mc.mineland.net
mc.renatusnetwork.com
us.shotbow.com
opblocks.com
ogsmp.net
hypixel.gamename.net
fun.mineteria.com
nightlymc.com
mcdiamondfire.com
spookmc.net
catgirls.xyz
furrymc.net
parlagames.co.il
mc-central.net
brayden.net
mc.pandacraft.cc
oceprestige.com
play.stardix.com
zero.minr.org
mc.pokeland.world
play.nzcraft.net
hypixel.mcip.life
pvp.thearchon.net
play.lastcraft.net
mc.minelatino.com
mc.paladium-pvp.fr
mchub.com
mc.classicsurvival.net
skyblock.com
zonix.us
play.saturn-x.space
tulipsurvival.com
uneasyvanilla.com
minelabs.es
mc.survival-games.cz
play.hyping.fr
jogar.mush.com.br
prison.airidale.net
n1mc.pl
play.ultimismc.com
pixel.mc-complex.com
topstrix.net
dreamsmp-mc.dreamsmp.club
mc.dexland.ru
minerival.org
oldfrog.org
mooncraft.es
og-sg.net
play.oneblockmc.com
srolemine.com
mc.survivaldub.com
jartexnetwork.com
play.foxmc.net
lgbt.dreamsmp.club
playmonumenta.com
dreamsmp.co
dreamsmp-public.dreamsmp.club
mc.mythonia.net
gamster.org
dreamsmp.dreamsmp.club
play.zedarmc.net
horstblocks.de
dream.dreamsmp.club
play.bumblecraft.net
skycraft.es
beedom.net
skeppy.dreamsmp.club
craftcube.pl
kingmc.pl
mc.mooncookie.top
play.minewind.com
15.235.14.112
griefergames.net
octc.ashcon.app
lifestealmc.net
dekitateserver.com
jartex.fun
mc.reallyworld.ru
click.dreamsmp.club
dreamsmp-play.dreamsmp.club
dreamsmp.dreamsmp.xyz
sapnap.dreamsmp.club
mineplex.mc-srv.com
ultimismc.com
vietmine.com
theolymp.tech
bedrock.dreamsmp.club
join.dreamsmp.club
real.dreamsmp.club
play.stratus.network
play.havocmc.net
deluxezone.net
chickencraft.nl
mc.thecavern.net
play.newwindserver.com
pvplands.net
2b2t.com
play.bendersmc.co
ruxor.net
woolwars.com
play.dreamsmp.club
mc.freakyville.net
play.blossomcraft.org
mc.advancius.net
play.imaginefun.net
mc.universocraft.es
vanillalegacy.com
play.democracycraft.net
oneblockmc.com
dojnaz.cloud
mineaqua.us
mc.fewer.live
mc.boucraft.net
dogecraft.net
redestone.com
ranboo.dreamsmp.club
2b2t.org.ru
dreamsmp-join.dreamsmp.club
dreamsmp-now.dreamsmp.club
public.dreamsmp.xyz
public.dreamsmp.club
mc.dreamsmp.club
dreamsmpmc.dreamsmp.club
coldpvp.org
minemen.mcip.life
pitsandbox.io
secret.dreamsmp.club
premium.vallenmc.net
mc.holyworld.ru
theseedmc.com
gtm.network
pvp.vanillalegacy.com
opblocks.net
penguin.gg
cloudegg.cloud
play.simplesurvival.gg
pika.host
play.applemc.fun
dankprison.com
pvp.bar
play.applecraft.org
mc.asgardsurvival.xyz
hypixel.oreify.tk
play.lovymc.com
play.kchscraft.net
mc.vypercraft.es
obsilion.es
java.dreamsmp.club
tubbo.dreamsmp.club
tommy.dreamsmp.club
bbh.dreamsmp.club
play.imc.re
play.pokesaga.org
play.lilacmc.net
mc.darkup.cz
opsucht.net
mc.minelibre.es
twerion.net
play.ccnetmc.com
play.apocgaming.org
play.pixelmonrealms.com
hub.megacrafting.com
prisonfun.com
play.feursmp.fr
mc.catcraft.net
wildkits.net
nexus1.su
hypixel.block-host.org
play.pokewild.com
mc.mineberry.net
massivecraft.com
inkmc.pl
deathzone.net
mc.serb-craft.com
play.fruitysmp.com
play.bridgescrims.net
zotticraft.net
gommehd.tk
mc.pokegalaxia.com
mc.aresmine.ru
play.hadaria.fr
scufflemc.net
mymg.pl
minefox.pl
mc.universocraft.org
play.melonsmp.fun
lytra.leonemc.net
juega.minebox.es
ngrief.su
purpleore.com
vanillaplus.net
mc.lostaroleros.com
ru.coldnetwork.net
infection.fun
play.vulengate.com
zedarmc.net
mineland.net
play.potterworldmc.com
mineblaze.ru
hytpc.mc.netease.com
kitpvp.us
nokbox.org
mc.atlanmc.com
brominemc.ru
play.rustex.org
lunar.pokewild.com
revengenetwork.es
mc.americraft.es
mc.voltyum.net
login.lordofthecraft.net
cosmicprisons.com
hub.madcraft.ir
ljaymc.pl
mc.jeracraft.net
jbwm.pl
play.valorhcf.net
eu.vimemc.net
zentic.cc
play.skyblock.top
hub.mc-complex.com
play.vanillaeuropa.com
mc.voxcraft.us
watermc.gg
play.sunnysurvival.com
tubboisafuckingsperg.fucktubbo.melih.ml
play.skyblocknetwork.com
mcfoxcraft.com
quarantena.rip
play.islet.world
mc.wynncraft.net
mc.champicraft.net
axelcraft.pl
blurkit.net
fawemc.me
mc.dextrality.xyz
play.minelc.com
play.moonlight.pub
voxyl.net
2b2t.minelatino.net
jjsmp.pl
mc.frenchsky.net
vortexnetwork.net
hypixel.es
moxmc.com
viperhcf.com
harrys.network
pika-network.net
survivalrolemine.no-ip.org
realcraft.pl
mineland.me
play.itsjerryandharry.com
play.togethercraft.online
nealand.club
minespazio.com
pactify.fr
2b2t.network
minetoday.org
guardiancraftbr.com
iostein.de
play.minesuperior.com
play.guildcraft.net
mc.prisonfun.com
teslacraft.org
play.chasecraft.gg
play.regorland.net
mc.fruitservers.net
creativefun.eu
flicked.net
bedwarspractice.net
oakhe.art
minearg.com
jogarbrasilcraft.com
mc.kriptonpvp.com
tubbo.is.a.jewish-nig.ga
vanillarealms.com
lobvers.net
snapcraft.net
bedwars.es
caraotacraft.top
coralmc.net
terramedia.club
mcgalaxycraft.com
play.haycube.net
extremecraft.net
pixelblockmc.com
cloutcraft.us
play.addicted2.ro
atlantismc.eu
hypixel.tk
og-smp.net
play.wynncraft.net
simmc.cc
pvpiq.pl
play.mineglobe.org
mcfallout.net
hololive.mcproxy.net
aussieanarchy.org
luvicraft.net
politmine.ru
play.vulturehub.com
mc.blockdrop.org
mlgrush.net
minerefuge.com
play.penguin.gg
mc.omegacraft.cl
mc.pixicraft.net
migosmc.ru
play.extremecraft.net
play.fyremc.hu
mc.eret.live
play.purpleprison.xyz
mc.originrealms.com
play.pokehub.org
snowycraft.net
mc.oresfallorigins.com
gg.prisonfun.com
play.pandakmc.fr
cosmicsurvival.com
tumbleweedmc.com
clearmc.pl
join-ml.com
anubis.gg
play.airidale.com
mc.hypermine.net
play.kings-craft.com
mc.performium.net
mc.sparklypower.net
play.voidpixel.ir
mc-gtm.net
duels.com.br
mc.imagineeringfun.net
mc.minecub.us
stelarmc.us
play.infusesmp.com
theuniverse.network
mc.eximradar.jp
medieval-vanilla.com
play.cubekrowd.net
mc.vanillalegacy.com
minevale.de
jogar.mc-mastercraft.net
us.survivaldub.com
mc.epicserver.biz
play.fluxpvp.net
play.townysmp.com
play.deathzone.net
archonhq.net
pixelmon.happycloudmc.com
mc.survivaldub.es
mc.bycraft.net
minearg.net
bausucht.net
play.peacefulfarms.net
play.alonefield.xyz
firecraft.dk
mc.ticocraft.com
shatteredvanilla.net
fusion-network.xyz
best.realprison.lol
chile.minelatino.com
constantiam.org
mineblaze.net
mc.cosmicmc.com
play.respawn.org
play.mineraze.net
eterniamc.net
play.avatarcraft.net
join.wildwoodsmp.com
play.semisurvivalcraft.com
soyvip.minelatino.com
play.evolucraft.fr
iostein.net
mc.queercraft.net
dreamsmpjoin.dreamsmp.club
oyna.chickennw.com
thestonedgolem.live
staff.minelatino.com
play.anubismc.com
mc.minelatino.net
aemine.vn
redestory.com
superawesome.dk
boxpvpv.net
mc.craftrise.network
join.dreamsmp.xyz
nekozouneko.com
builds.kr
boatsnbunnies.com
skyblocky.com
underblock.gg
2b2t.rocks
play.craftadia.com
play.vexusmc.net
enchantedcraft.us
bycraft.xyz
hub.mcs.gg
play.pokezone.net
mineserwer.pl
dexland.su
tkcraft.com.br
play.prismforge.com
minecraftbrasil.com
mc.skyblock.tc
play.prismparty.net
lecraft.pl
poglords.net
play.flaremc.org
peru.minelatino.com
play.minetopia.nl
mc.soulpixel.lat
minelucky.org
mc.ultranetwork.net
faderealms.org
faderealms.com
neocubest.com
topstrix.com
empireminecraft.com
play.popularmmosworld.com
play.bolt.oc.tc
play.onlymc.net
lemoncloud.net
play.kikkercraft.nl
play.viperhcf.net
play.civmc.net
xmcsv.in
demonicpvp.org
play.awitamc.net
play.saloonnetwork.com
jogar.austv.net
beta.playmonumenta.com
gommehd.com
play.pokefind.co
play.hycraft.us
sunnysurvival.com
mc.ecocitycraft.com
finerpg.pl
arkraft.pro
3b3t.ru
play.freshsmp.fun
bedwars.games
hyperlandsmc.tk
play.soulcraft.network
tavernmc.net
ozonemc.ru
minefort.com
camman.cyborgmc.com
syferhcf.us
2.56.247.25
mc.mineberry.org
mc.craftrise.tc
balancedguild.tk
salc1.org
2b2t.pe
5b5t.pe
simpcraft.net
2b2tclones.com
5b5t.com
simpcraft.org
bartolsmp.com
jogar.absolutgg.com.br
mc.masedworld.net
randomkits.net
play.minelatino.net
pixelmoncraft.com
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
pixelmoncraft.com
mc.bycraft.xyz
mc.ignisnw.com
supersmp.net
mc.continuitycraft.us
simplyvanilla.net
dwarvencraft.net
bamboss.mossmc.top
lifestealsmp.com
play.yomnetwork.ca
play.rebirthofbalkan.com
play.sheepcraft.org
join.performium.co
dreamsmpplay.dreamsmp.club
hub.hyneo.ru
eu.wynncraft.net
lemoncloud.org
plateou.gg
mc.svrealcraft.pl
server-de-kirzu.krzu.me
play.madcraft.ir
potterworldmc.com
jartexnetwork.net
mc.nekobox.es
`;
        const lines = fileContents.split("\n");
        console.log(lines); // Check the lines array in the console
        const randomIndex = Math.floor(Math.random() * lines.length);
        console.log(randomIndex + "11"); // Check the random index in the console
        const randomLine = lines[randomIndex];
        console.log(randomLine, "?"); // Check the random line in the console
        this.randomLine = randomLine.trim();
        console.log(this.randomLine); // Check if randomLine is properly assigned
      } catch (error) {
        console.error(error);
      }
    },
  },
};
</script>



<style scoped>
.container {
  display: inline;
  flex-direction: column;
  height: 100%;
}

.nav {
  background-color: #272727;
  padding: 10px;
  margin-bottom: 20px;
  max-width: 500px; /* added */
  margin: 0 auto; /* added */
}

.nav ul {
  list-style: none;
  margin: 0;
  padding: 0;
}

.nav li {
  display: inline-block;
  margin-right: 15px;
}

.nav-item {
  color: rgb(165, 139, 139);
  text-decoration: none;
  font-weight: bold;
  font-size: 18px;
  padding: 10px;
  border-radius: 5px;
  transition: background-color 0.3s ease-in-out;
}

.nav-item:hover {
  background-color: #ddd;
}

.content {
  flex: 1;
}
</style>
